services:
  - type: web
    name: cryptopulse-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: cryptopulse-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cryptopulse-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: cryptopulse-db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: cryptopulse-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: cryptopulse-db
          property: password

databases:
  - name: cryptopulse-db
    databaseName: cryptopulse
    plan: free
